### ISSUE TITLE
calling next when exception throwed

### ISSUE THREAD

**Issue by guftall** [aliNejati-bu/express-typescript-starter#1]
روتر اکسپرس هنوز پرامیس رو ساپورت نمیکنه. اگه متد های async کنترلرهات اکسپشن بدن توی نسخه های قبلی node ریسپانسی نمیگیری، جدید تر ها هم اپ کرش میکنه بخاطر uncatched promise. چند تا راه حل داره سرچ کنی
https://github.com/aliNejati-bu/express-typescript-starter/blob/0e3bdfdf09e2a1029ad9e8ca17040e35d341d1a8/src/Controller/index.ts#L41

+‌کانفیگ هات رو همه بذار توی یک فایل، بعدا نخوای دنبالشون بگردی. و اگه خواستی علاوه بر env از جای دیگه بخونی راحت باشه

**Comment by aliNejati-bu** [comment]
ممنونم بابت نکته عالی که یاد آوری کردی.
توی هلپر ها یه تابع `asyncWrapper` ساختم و اکسپشن ها رو اونجا مدیریت کردم.
https://github.com/aliNejati-bu/express-typescript-starter/blob/e9e445fea54c3be75e6ce131e4820a1014171539/src/helpers/functions.ts#L31

در نهایت توی کنترلر بیس اومدم و همه اکشن ها و میدلور ها رو دادم به asyncWrapper.
https://github.com/aliNejati-bu/express-typescript-starter/blob/e9e445fea54c3be75e6ce131e4820a1014171539/src/Controller/index.ts#L28

**Comment by guftall** [comment]
nice
